env:
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "react-hooks"

rules:
  "prettier/prettier": "error"
  "react-hooks/rules-of-hooks": "error"
  "react-hooks/exhaustive-deps": "warn"

